### PR TITLE
Add support for S_UDT and S_UDT_ST

### PR DESCRIPTION
**Pull request by wroyca**
Signed-off-by: William Roy <wroy@pm.me>

### CODE REVIEW

**Comment by wroyca** [comment]
It seems that some of them are not recovered, but I don't know exactly how or why

**Comment by MolecularMatters** [comment]
Which information are you looking for?
As far as I know, the type descrptions of all types (whether user-defined or not) are found in the TPI stream.

**Comment by wroyca** [comment]
> Which information are you looking for? As far as I know, the type descrptions of all types (whether user-defined or not) are found in the TPI stream.

Sorry, it was not clear. I'm only looking for the structures.  I was under the impression that the names of the structures were to be retrieved via the UDT first, then their type index was to be passed to the TPI stream to get the fields and such. Maybe I was wrong? For example, raw_pdb can retrieve about 10/20k UDTs with this PR but there are quite a few missing structures that I would like to pass to my — currently not pushed — TPI stream implementation.

**Comment by MolecularMatters** [comment]
What you describe sounds reasonable, so I wonder where the problem lies.
Do you have a minimal repro or something that reproduces the problem, i.e. not all user-defined types being listed in the DBI stream?

**Comment by wroyca** [comment]
> What you describe sounds reasonable, so I wonder where the problem lies. Do you have a minimal repro or something that reproduces the problem, i.e. not all user-defined types being listed in the DBI stream?

Unfortunately, the PDBs I use are not allowed to be distributed. However, I think that these open-source repositories should be able to reproduce the problem. If this is not the case, you can contact me by email or on discord wroy#5887.

https://github.com/JACoders/OpenJK
https://github.com/id-Software/Quake-III-Arena

**Comment by wroyca** [comment]
It turns out that this was my mistake. I forgot about typealias. Everything is OK and works as expected. It's ready to be merged. 👍

**Pull request merged**
