### PR TITLE
CMake integration + GitHub actions

### PR DESCRIPTION
**Pull request by ZehMatt**
There are a couple of changes I made in order to get this working.
1. I moved the includes to be domain specific, so one can use ```#include <raw_pdb/*> ```
2. I had to modify the way PDB_ASSERT works, instead of supplying a custom msg it now prints the condition instead, I tried to get it working but clang/gcc don't really like it when variadic parameters are discarded.
3. I moved the examples into the root folder, I don't think its a good idea to mix files like that.
4. Had to stub out the memory mapped file, I will look into adding the linux/posix equivalent soon.
5. Bunch of smaller code fixes

### CODE REVIEW

**Review by MolecularMatters — CHANGES_REQUESTED** [review]
Thank you for providing support for Linux. There is another PR that will be merged soon that has support for memory-mapped files in the examples.
I agree with the restructuring of src/include/examples, but there are a few things that require fixing before this can be merged:

* Please do not delete the Visual Studio projects and solution.
* The PDB_ASSERT implementation needs to be fixed to work across MSVC, Clang, and GCC. This should be possible.
* Do not get rid of PDB_NO_ALIAS. If other compilers don't have similar attributes/features, define an empty macro instead.
* Similarly, do not get rid of the PDB_FLEXIBLE_ARRAY_MEMBER macro, since it makes the intent more clear and doesn't have disabled warnings sprinkled across files where it's needed, but rather in one place.

**Comment by ZehMatt** [comment]
> Thank you for providing support for Linux. There is another PR that will be merged soon that has support for memory-mapped files in the examples. I agree with the restructuring of src/include/examples, but there are a few things that require fixing before this can be merged:
> 
> * Please do not delete the Visual Studio projects and solution.
> * The PDB_ASSERT implementation needs to be fixed to work across MSVC, Clang, and GCC. This should be possible.
> * Do not get rid of PDB_NO_ALIAS. If other compilers don't have similar attributes/features, define an empty macro instead.
> * Similarly, do not get rid of the PDB_FLEXIBLE_ARRAY_MEMBER macro, since it makes the intent more clear and doesn't have disabled warnings sprinkled across files where it's needed, but rather in one place.

I disagree on serval points.
* Visual Studio solution is quite useless if you have cmake, I wouldn't wanna bother updating two things, just use "cmake . -B msvc" on Windows and you get projects generated by cmake.
* PDB_ASSERT was overly complicated, I reduced it to be just a condition and the output is the condition itsself.
* PDB_NO_ALIAS aka restrict is not recommended with C++, after all this compiles as C++ and not C99 and you will not really get anything out of it.
* PDB_FLEXIBLE_ARRAY_MEMBER, please no.

I was fighting the code for serval hours to get it working with GCC and Clang, this is the result of it.

**Comment by MolecularMatters** [comment]
>     * Visual Studio solution is quite useless if you have cmake, I wouldn't wanna bother updating two things, just use "cmake . -B msvc" on Windows and you get projects generated by cmake.

It's not useless for people that don't ever use cmake, myself included. In the Windows world, providing a Visual Studio solution for people to open out-of-the-box is considered a bare minimum.

>     * PDB_ASSERT was overly complicated, I reduced it to be just a condition and the output is the condition itsself.

I don't think it was overly complicated. It provides a means to output a formatted string along with the condition, which is helpful in many cases where the condition alone is not that useful, e.g. an out-of-bounds access.
The message "out-of-bounds" doesn't convey much information, whereas it makes a huge difference whether I see "out-of-bounds, index 10 of 9" or "out-of-bounds, index 0xffffffff of 9".
One is an off-by-one error, the other is an overflow.

>     * PDB_NO_ALIAS aka restrict is not recommended with C++, after all this compiles as C++ and not C99 and you will not really get anything out of it.

The restrict you're talking about (__restrict__ or __restrict, depending on the compiler) is useful in C++ as well - I could link to several blogs and articles where this is useful, i.e. in game development, but that's another topic.
PDB_NO_ALIAS is defined to be __declspec(restrict) though, which is something entirely different than the C99 restrict!

>     * PDB_FLEXIBLE_ARRAY_MEMBER, please no.

Agree to disagree on this front.

**Comment by ZehMatt** [comment]
> It's not useless for people that don't ever use cmake, myself included. In the Windows world, providing a Visual Studio solution for people to open out-of-the-box is considered a bare minimum.

Well okay, not gonna argue with that. Visual Studio has native cmake support in case you didn't know, so I'm not sure what exactly the benefit is of keeping the project when you can just open the cmake file

> I don't think it was overly complicated. It provides a means to output a formatted string along with the condition, which is helpful in many cases where the condition alone is not that useful, e.g. an out-of-bounds access. The message "out-of-bounds" doesn't convey much information, whereas it makes a huge difference whether I see "out-of-bounds, index 10 of 9" or "out-of-bounds, index 0xffffffff of 9". One is an off-by-one error, the other is an overflow.

I can somewhat agree on that, however asserts also typically cause a debug break/int3/software breakpoint for the user to inspect it and its not meant to really print something. Also if you want to properly display values consider using better assertion helpers ex.:
```assertions::neq(a, b);```
GCC is not happy with the variadic macro usage and only with C++20 we could get around it, the point of the warnings is not really to just suppress them, especially not when project claims to be high quality code, I strongly disagree with code that ignores a ton of warnings.

> The restrict you're talking about (**restrict** or __restrict, depending on the compiler) is useful in C++ as well - I could link to several blogs and articles where this is useful, i.e. in game development, but that's another topic. PDB_NO_ALIAS is defined to be __declspec(restrict) though, which is something entirely different than the C99 restrict!

Does it actually influence the code gen? Have you checked the output? I generally don't agree with compiler specific things that clutter the codebase for maybe the additional 0.001% extra performance. Compilers are already pretty good at figuring out things on their own, I however can see how MSVC requires a lot of massaging because its generally bad.

**Comment by MolecularMatters** [comment]
> > It's not useless for people that don't ever use cmake, myself included. In the Windows world, providing a Visual Studio solution for people to open out-of-the-box is considered a bare minimum.
> 
> Well okay, not gonna argue with that. Visual Studio has native cmake support in case you didn't know.

I know it has, but I don't want to have anything to do with CMake.

> > I don't think it was overly complicated. It provides a means to output a formatted string along with the condition, which is helpful in many cases where the condition alone is not that useful, e.g. an out-of-bounds access. The message "out-of-bounds" doesn't convey much information, whereas it makes a huge difference whether I see "out-of-bounds, index 10 of 9" or "out-of-bounds, index 0xffffffff of 9". One is an off-by-one error, the other is an overflow.
> 
> I can somewhat agree on that, however asserts also typically cause a debug break/int3/software breakpoint for the user to inspect it and its not meant to really print something.

Sure, and that's useful when you're in front of a debugger. As soon as the code is integrated somewhere, chances are you no longer aren't.

> GCC is not happy with the variadic macro usage and only with C++20 we could get around it, the point of the warnings is not really to just suppress them

What is the warning given by GCC?

> especially not when project claims to be high quality code, I strongly disagree with code that ignores a ton of warnings.

Can you show me where the library ignores a ton of warnings?
If you can raise specific issues, I'd be happy to improve them.
As far as I can see right now, the library itself disables warnings which are informational (e.g. a function was not inlined), or warnings which cannot be worked around (e.g. because C++ exceptions are disabled).
All other warnings should be suppressed in place, e.g. because flexible array members are not standardized in C++, which is a pity. I'd rather have that contained in a macro than disable or suppress it on a per-file level or similar.

> > The restrict you're talking about (**restrict** or __restrict, depending on the compiler) is useful in C++ as well - I could link to several blogs and articles where this is useful, i.e. in game development, but that's another topic. PDB_NO_ALIAS is defined to be __declspec(restrict) though, which is something entirely different than the C99 restrict!
> 
> Does it actually influence the code gen? Have you checked the output? I generally don't agree with compiler specific things that clutter the codebase for maybe the additional 0.001% extra performance. Compilers are already pretty good at figuring out things on their own, I however can see how MSVC requires a lot of massaging because its generally bad.

As you said, MSVC is not good at figuring things out, since it has no type-based alias analysis at all. It assumes aliasing everywhere, even across non-compatible types.

**Comment by ZehMatt** [comment]
I don't quite remember the warning, it was either having a comma too much or it warned that the variadic arguments arent used/discard. Anyway feel free to tinker around with this branch, you'll see all the warnings on the CI if you revert some things. As for the restrict I think I also didn't want it because of where attributes go, I think GCC/MSVC have different placements here so there was no good way of doing it via macros. There are quite a lot of specific things that I don't quite remember, to be fair it wasn't the best idea to squash my commits but it was also a huge mess for anyone to review.

**Pull request closed without merging**
